apiVersion: v1
kind: Pod
metadata:
  name: mybox2
spec:
  restartPolicy: Always
  containers:
  - name: mybox
    image: busybox
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 250m
        memory: 256Mi    
    volumeMounts:
      - name: mysecret
        mountPath: /etc/myapp
        readOnly: true
    command:
      - sleep
      - "3600"
  volumes:
    - name: mysecret
      secret:
        secretName: secrets2
