apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-managed-disk
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: hostpath
  resources:
    requests:
      storage: 10Gi
